name: Release Creation

on:
  release:
    types: [published]

jobs:
  build:
    container:
      image: electronuserland/builder:wine
      options: --user github-runner
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn dist
      - name: Update Release with Files
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: ${{ github.event.release.name }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "./dist/vtt-n1xx1.exe"
          tag: ${{ github.event.release.tag_name }}
          body: ${{ github.event.release.body }}
